{
    "name": "FiveFive Custom Module",
    "version": "1.0.0",
    "summary": "User for FiveFive company",
    "author": "FiveFive Developer",
    "depends": ["base", "mail"],
    "external_dependencies": {
        "python": ["Pillow", "python-barcode"],
    },
    "assets": {
        "web.assets_backend": [
            "fivefive_custom/static/src/scss/fivefive_purchase_order_form.scss",
            "fivefive_custom/static/src/js/list_confirm_delete.js",
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        "data/purchase_order_sequence.xml",
        "views/purchase_order/table_view.xml",
        "views/purchase_order/cancel_wizard.xml",
        "views/purchase_order/form_view.xml",
        "views/supplier/table_view.xml",
        "views/supplier/form_view.xml",
        "views/logistic/table_view.xml",
        "views/logistic/form_view.xml",
        "views/store/table_view.xml",
        "views/store/form_view.xml",
        "views/product/table_view.xml",
        "views/product/form_view.xml",
        "views/inventory/table_view.xml",
        "views/inventory/form_view.xml",
        "views/warehouse/table_view.xml",
        "views/warehouse/form_view.xml",
        "views/purchase_order_document/upload_wizard.xml",
        "views/purchase_order_document/table_view.xml",
        "views/purchase_order_document/form_view.xml",
        "views/menu_view.xml",
    ],
    "installable": True,
    "auto_install": False,
    "post_init_hook": "hooks.post_init_hook",
}
