{
    "name": "FiveFive Custom Module",
    "version": "1.0.4",
    "summary": "User for FiveFive company",
    "author": "FiveFive Developer",
    "depends": ["base", "mail", "web"],
    "external_dependencies": {
        "python": ["Pillow", "python-barcode"],
    },
    "assets": {
        "web.assets_backend": [
            "fivefive_custom/static/src/scss/fivefive_purchase_order_form.scss",
            "fivefive_custom/static/src/scss/fivefive_inventory_form.scss",
            "fivefive_custom/static/src/scss/fivefive_list_headers.scss",
            "fivefive_custom/static/src/js/list_header_full_text.js",
            "fivefive_custom/static/src/js/list_confirm_delete.js",
            "fivefive_custom/static/src/js/inventory_list_aggregate.js",
            "fivefive_custom/static/src/js/purchase_order_supplier_credit.js",
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        "data/purchase_order_sequence.xml",
        "data/inventory_cron.xml",
        "views/purchase_order/table_view.xml",
        "views/purchase_order/pay_wizard.xml",
        "views/purchase_order/clearing_wizard.xml",
        "views/purchase_order/close_wizard.xml",
        "views/purchase_order/supplier_credit_manual_wizard.xml",
        "views/purchase_order/supplier_credit_apply_wizard.xml",
        "views/inventory/store_inventory_convert_wizard.xml",
        "views/purchase_order/cancel_clearing_wizard.xml",
        "views/purchase_order/payment_cancel_wizard.xml",
        "views/purchase_order/cancel_wizard.xml",
        "views/purchase_order/form_view.xml",
        "views/purchase_order/convert_to_product_wizard.xml",
        "views/purchase_order/convert_add_line_wizard.xml",
        "views/purchase_order/add_convert_wizard.xml",
        "views/purchase_order/convert_cost_wizard.xml",
        "views/purchase_order/product_convert_views.xml",
        "views/supplier/table_view.xml",
        "views/supplier/form_view.xml",
        "views/logistic/table_view.xml",
        "views/logistic/form_view.xml",
        "views/store/table_view.xml",
        "views/store/form_view.xml",
        "views/res_company_views.xml",
        "views/product/table_view.xml",
        "views/product/form_view.xml",
        "views/inventory/table_view.xml",
        "views/inventory/form_view.xml",
        "views/inventory/warehouse_transfer_wizard.xml",
        "views/inventory/warehouse_inventory_receipt_wizard.xml",
        "views/inventory/store_inventory_adjust_wizard.xml",
        "views/pos/pos_templates.xml",
        "views/pos/pos_views.xml",
        "views/pos/pos_receipt_template.xml",
        "views/pos/requisition_views.xml",
        "views/warehouse/table_view.xml",
        "views/warehouse/form_view.xml",
        "views/purchase_order_document/upload_wizard.xml",
        "views/purchase_order_document/table_view.xml",
        "views/purchase_order_document/form_view.xml",
        "views/menu_view.xml",
    ],
    "installable": True,
    "auto_install": False,
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
}
